#!/bin/bash 
#! application name
application="./check_results"

#! Run options for the application
options="results/av_vels_300x200.dat results/final_state_300x200.dat"

###############################################################
### You should not have to change anything below this line ####
###############################################################

#! Run the executable
$application $options

