#!/bin/bash 
#!
#! Sample PBS file
#!
#! Name of job

#PBS -N coursework_two
#PBS -joe
#PBS -q veryshort

#! Number of nodes (in this case 1 node with 8 CPU cores)
#! The total number of nodes passed to mpirun will be nodes*ppn 
#! Second entry: Total amount of wall-clock time (true time). 
#! 02:00:00 indicates 02 hours

#PBS -l nodes=1:ppn=3,walltime=02:00:00

#! Mail to user if job aborts
#PBS -m a

#! application name
application="./d2q9-bgk.exe"

#! Run options for the application
options="input_30x20.params obstacles_30x20.dat"

###############################################################
### You should not have to change anything below this line ####
###############################################################

#! change the working directory (default is home directory)

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:
echo `cat $PBS_NODEFILE | uniq`
 
#! Create a machine file for MPI
cat $PBS_NODEFILE > machine.file.$PBS_JOBID
 
numnodes=`wc $PBS_NODEFILE | awk '{ print $1 }'`

export OMP_NUM_THREADS=$numnodes

#! Run the executable
mpirun -np $numnodes -machinefile machine.file.$PBS_JOBID $application $options

./check_results results/av_vels_30x20.dat results/final_state_30x20.dat
