#!/bin/bash 
#!
#! Sample PBS file
#!
#! Name of job

#PBS -N coursework_two
#PBS -joe
#PBS -q veryshort

#! Number of nodes (in this case 1 node with 8 CPU cores)
#! The total number of nodes passed to mpirun will be nodes*ppn 
#! Second entry: Total amount of wall-clock time (true time). 
#! 02:00:00 indicates 02 hours

#PBS -l nodes=4:ppn=4,walltime=02:00:00

#! Mail to user if job aborts
#PBS -m a

#! application name
application="./d2q9-bgk.exe"

#! Run options for the application
options="input_300x200.params obstacles_300x200.dat"

###############################################################
### You should not have to change anything below this line ####
###############################################################

#! change the working directory (default is home directory)

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:
echo `cat $PBS_NODEFILE | uniq`
 
#! Create a machine file for MPI
cat $PBS_NODEFILE | uniq > machine.file.$PBS_JOBID
 
numnodes=`wc -l machine.file.$PBS_JOBID | awk '{ print $1 }'`
numthreads=2
procspernode=4
numprocs=$((($numnodes*$procspernode)/$numthreads))
export OMP_NUM_THREADS=$numthreads

#! Run the executable
mpirun -np $numprocs -machinefile machine.file.$PBS_JOBID --cpus-per-proc $numthreads -x OMP_NUM_THREADS $application $options
